FROM python:3.10-slim

WORKDIR /usr/app

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir dbt-trino==1.7.0

ENTRYPOINT ["tail", "-f", "/dev/null"]